// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn5zzgaXi5h6B12bnD2idS2Ji1Aj2KZUk',
    appId: '1:256026000290:web:688e625de3eec35367d0fb',
    messagingSenderId: '256026000290',
    projectId: 'snapjam-523',
    authDomain: 'snapjam-523.firebaseapp.com',
    storageBucket: 'snapjam-523.appspot.com',
    measurementId: 'G-Q0GGBHN0CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmVHsVMmaOqxeJ7AGa9XhpFLyAxZueSk',
    appId: '1:256026000290:android:f544931e93ba243367d0fb',
    messagingSenderId: '256026000290',
    projectId: 'snapjam-523',
    storageBucket: 'snapjam-523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-bQcnCkPyYc4s38HZwKCx3Nx8xw7jRk',
    appId: '1:256026000290:ios:b5743256d08947da67d0fb',
    messagingSenderId: '256026000290',
    projectId: 'snapjam-523',
    storageBucket: 'snapjam-523.appspot.com',
    iosClientId: '256026000290-asr2q6i9k0dv0c7uaev7iv79595hdofg.apps.googleusercontent.com',
    iosBundleId: 'com.CutawayShotGames.snapjam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ-bQcnCkPyYc4s38HZwKCx3Nx8xw7jRk',
    appId: '1:256026000290:ios:b5743256d08947da67d0fb',
    messagingSenderId: '256026000290',
    projectId: 'snapjam-523',
    storageBucket: 'snapjam-523.appspot.com',
    iosClientId: '256026000290-asr2q6i9k0dv0c7uaev7iv79595hdofg.apps.googleusercontent.com',
    iosBundleId: 'com.CutawayShotGames.snapjam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn5zzgaXi5h6B12bnD2idS2Ji1Aj2KZUk',
    appId: '1:256026000290:web:97998e9562c6dd2167d0fb',
    messagingSenderId: '256026000290',
    projectId: 'snapjam-523',
    authDomain: 'snapjam-523.firebaseapp.com',
    storageBucket: 'snapjam-523.appspot.com',
    measurementId: 'G-0G2H9H5WPL',
  );
}
